version: "3.3"
services:
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    image: rabbitmq:3-management
  
  fibonaccifirst:
    container_name: fibonacciFirst
    ports:
      - 8000:80
      - 8001:443
    #environment:
    #    - "ASPNETCORE_URLS=https://+;http://+"
    #    - Kestrel__Certificates__Default__Path=/app/Infrastructure/Certificate/cert-aspnetcore.pfx
    #    - Kestrel__Certificates__Default__Password=SecretPassword        
    build:
      context: ./src
      dockerfile: FibonacciFirst/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
  
  fibonaccisecond:
    container_name: fibonacciSecond
    ports:
      - 9000:80
      - 9001:443
    #environment:
    #    - "ASPNETCORE_URLS=https://+;http://+"
    #    - Kestrel__Certificates__Default__Path=/app/Infrastructure/Certificate/cert-aspnetcore.pfx
    #    - Kestrel__Certificates__Default__Password=SecretPassword       
    build:
      context: ./src
      dockerfile: FibonacciSecond/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq            